### ISSUE TITLE
mini_io.h file missing

### ISSUE THREAD

**Issue by rcadena** [bitbank2/bbgfx#1]
Hi Larry,

can't wait to try out this library.  When I ran the make command the compiler reported a missing header file:

```
$ make
cc -c -Wall -O2 bbgfx_helper.c
bbgfx_helper.c:31:21: fatal error: mini_io.h: No such file or directory
 #include <mini_io.h>
                     ^
compilation terminated.
Makefile:14: recipe for target 'bbgfx_helper.o' failed
```

I thought maybe one of your other repos had the miniio library, but, no dice.  Thanks in advance.

**Comment by bitbank2** [comment]
Sorry about the delay. I just pushed changes which fix everything and have released the source code to my "mini" portable imaging library.

**Comment by rcadena** [comment]
Awesome. Thanks!
